[metadata]
author = "Jacob Hummer <jcbhmr@outlook.com> (https://jcbhmr.com)"
description = "TODO"
license = "MIT OR Apache-2.0"
homepage = "https://jcbhmr.github.io/vin-info-wasm/"
repository = "https://github.com/jcbhmr/vin-info-wasm"
